export const skills: string[] = [
    "TypeScript",
    "JavaScript",
    "React",
    "NextJS",
    "NodeJS",
    "Vue",
    "Laravel",
    "C#",
    "TailwindCSS",
    "Postgres",
    "MongoDB",
    "Python",
    "Docker",
    "Git",
];